"""Optional: create a local VM to run pless against.

Not a kind of host — a way to obtain one. Both backends end by producing an SSH
config file, so from every other module's point of view a VM is an ordinary
machine reached over SSH.

Two backends, each mirroring a production path:
  lima      -> Debian, provisioned by `pless bootstrap` (like a Pi)
  multipass -> Ubuntu, provisioned by cloud-init (like a cloud server)
"""

from __future__ import annotations

import getpass
import json
import shutil
import subprocess
from pathlib import Path

from pless import config

# The current Ubuntu LTS. Older releases remain supported by bootstrap; we test
# against what we recommend.
UBUNTU_IMAGE = "26.04"
LIMA_TEMPLATE = "template://debian-13"

BACKENDS = ("lima", "multipass")

INSTALL_HINTS = {
    "limactl": "Install it with `brew install lima`.",
    "multipass": "Install it with `brew install --cask multipass`.",
}


class VmError(RuntimeError):
    pass


def require_backend(backend: str) -> None:
    if backend not in BACKENDS:
        raise VmError(f"Unknown vm.backend {backend!r} (valid: {', '.join(BACKENDS)}).")
    tool = "limactl" if backend == "lima" else "multipass"
    if shutil.which(tool) is None:
        raise VmError(f"{tool} is not installed. {INSTALL_HINTS[tool]}")


def _run(tool: str, args: list[str], timeout: int = 900) -> subprocess.CompletedProcess[str]:
    return subprocess.run([tool, *args], capture_output=True, text=True, timeout=timeout)


def _lima_instance(name: str) -> dict | None:
    completed = _run("limactl", ["list", "--format", "json"], timeout=30)
    for line in completed.stdout.strip().splitlines():
        try:
            data = json.loads(line)
        except json.JSONDecodeError:
            continue  # limactl may print warnings before the JSON
        if data.get("name") == name:
            return data
    return None


def _multipass_instance(name: str) -> dict | None:
    completed = _run("multipass", ["info", name, "--format", "json"], timeout=30)
    if completed.returncode != 0:
        return None
    return json.loads(completed.stdout)["info"][name]


def exists(cfg: config.VmConfig) -> bool:
    if cfg.backend == "lima":
        return _lima_instance(cfg.name) is not None
    return _multipass_instance(cfg.name) is not None


def info(cfg: config.VmConfig) -> dict:
    """Normalised status: {'state': str, 'addresses': list[str]}."""
    if cfg.backend == "lima":
        data = _lima_instance(cfg.name)
        if data is None:
            raise VmError(f"Lima does not know a VM named {cfg.name!r}.")
        port = data.get("sshLocalPort")
        return {
            "state": data.get("status", "unknown"),
            "addresses": [f"127.0.0.1:{port}"] if port else [],
        }

    data = _multipass_instance(cfg.name)
    if data is None:
        raise VmError(f"Multipass does not know a VM named {cfg.name!r}.")
    return {"state": data.get("state", "unknown"), "addresses": data.get("ipv4") or []}


def render_multipass_ssh_config(name: str, address: str, user: str, key_path: Path) -> str:
    """Multipass has no SSH config of its own, so we write one.

    That keeps both backends identical to the rest of the codebase: a host is
    an SSH config entry, whatever produced it.
    """
    return (
        f"# Written by pless for the multipass VM {name!r}.\n"
        "# Regenerated by `pless vm create`; edits will be lost.\n"
        f"Host {name}\n"
        f"  Hostname {address}\n"
        f"  User {user}\n"
        f"  IdentityFile {key_path}\n"
        "  StrictHostKeyChecking accept-new\n"
        "  IdentitiesOnly yes\n"
    )


def lima_ssh_config_path(name: str) -> Path:
    """Lima writes this itself and rewrites it on restart, so the port stays current."""
    return Path.home() / ".lima" / name / "ssh.config"


def multipass_ssh_config_path(name: str) -> Path:
    return Path.home() / ".config" / "pless" / f"{name}.ssh.config"


def ssh_config_for(cfg: config.VmConfig, ssh_key: Path) -> tuple[Path, str]:
    """Return (config path, host alias) for a running VM, writing one if needed."""
    if cfg.backend == "lima":
        path = lima_ssh_config_path(cfg.name)
        if not path.is_file():
            raise VmError(f"Lima has not written {path} — is the VM running?")
        return path, f"lima-{cfg.name}"

    data = info(cfg)
    if not data["addresses"]:
        raise VmError(f"VM {cfg.name!r} has no address yet (state: {data['state']}).")
    path = multipass_ssh_config_path(cfg.name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_multipass_ssh_config(cfg.name, data["addresses"][0], "ubuntu", ssh_key))
    return path, cfg.name


def launch(cfg: config.VmConfig, user_data_path: Path | None = None) -> None:
    """Create the VM, blocking until it is up. First run downloads an image.

    Lima gets no cloud-init: it is provisioned by `pless bootstrap` over SSH,
    exactly as a Pi is. Multipass gets the host spec as cloud-init, as a cloud
    server does.
    """
    if cfg.backend == "lima":
        completed = _run(
            "limactl",
            [
                "start",
                LIMA_TEMPLATE,
                f"--name={cfg.name}",
                f"--cpus={cfg.cpus}",
                f"--memory={cfg.memory_gb}",
                f"--disk={cfg.disk_gb}",
                "--tty=false",
            ],
        )
        if completed.returncode != 0:
            raise VmError(f"limactl start failed: {completed.stderr.strip()}")
        return

    if user_data_path is None:
        raise VmError("The multipass backend requires cloud-init user-data.")
    completed = _run(
        "multipass",
        [
            "launch",
            UBUNTU_IMAGE,
            "--name",
            cfg.name,
            "--cpus",
            str(cfg.cpus),
            "--memory",
            cfg.memory,
            "--disk",
            cfg.disk,
            "--cloud-init",
            str(user_data_path),
        ],
    )
    if completed.returncode != 0:
        raise VmError(f"multipass launch failed: {completed.stderr.strip()}")


def delete(cfg: config.VmConfig) -> None:
    if cfg.backend == "lima":
        stop = _run("limactl", ["stop", "--force", cfg.name], timeout=120)
        if stop.returncode != 0 and "not running" not in stop.stderr.lower():
            raise VmError(f"limactl stop failed: {stop.stderr.strip()}")
        completed = _run("limactl", ["delete", "--force", cfg.name], timeout=120)
        if completed.returncode != 0:
            raise VmError(f"limactl delete failed: {completed.stderr.strip()}")
    else:
        completed = _run("multipass", ["delete", "--purge", cfg.name], timeout=120)
        if completed.returncode != 0:
            raise VmError(f"multipass delete failed: {completed.stderr.strip()}")
        multipass_ssh_config_path(cfg.name).unlink(missing_ok=True)


def default_user() -> str:
    return getpass.getuser()
